name: Build firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Restore PlatformIO cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pio-
      - name: Install PlatformIO
        run: pip install platformio
      - name: Install clang tools
        run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy
      - name: Run clang-format
        uses: reviewdog/action-clang-format@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: false
          pattern: |
            src/**/*.cpp
            include/**/*.h
      - name: Run clang-tidy
        uses: reviewdog/action-clang-tidy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: false
          clang_tidy_flags: '-Iinclude -std=c++17'
      - name: Build
        run: pio run -e m5stack-cores3
