name: Build firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Restore PlatformIO cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pio-
      - name: Install PlatformIO
        run: pip install platformio
      - name: Install clang tools
        run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy
      - name: Run clang-format
        run: |
          clang-format -n --Werror $(find src include -name '*.cpp' -o -name '*.h')
      - name: Run clang-tidy
        run: |
          clang-tidy $(find src -name '*.cpp') -- -Iinclude -std=c++17
      - name: Build
        run: pio run -e m5stack-cores3
