name: Build firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: pip キャッシュを復元
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: PlatformIO キャッシュを復元
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: ${{ runner.os }}-pio-
      - name: PlatformIO をインストール
        run: pip install platformio
      - name: ビルド
        run: pio run -e m5stack-cores3
