name: PlatformIO Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python を設定
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: pipキャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: PlatformIOキャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: PlatformIO インストール
        run: pip install platformio

      - name: intelhex インストール
        run: pip install intelhex

      - name: ビルド
        run: pio run -e m5stack-cores3

      - name: ファームウェアをアーティファクトで保存
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/m5stack-cores3/firmware.bin
