name: PlatformIO Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python を設定
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: pipキャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: PlatformIOキャッシュ
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-
        # ネットワークが制限される環境では上記ディレクトリを事前に用意してください

      - name: PlatformIO インストール
        run: pip install platformio

      - name: テスト実行
        run: pio test -e m5stack-cores3
